const loginCopy = {
  ar: {
    identifier: "البريد الإلكتروني أو اسم المستخدم أو رقم الهاتف",
    password: "كلمة المرور",
    signingIn: "جاري تسجيل الدخول...",
    failed: "تعذر تسجيل الدخول. تحقق من البيانات ثم حاول مرة أخرى.",
    verificationRequired: "يجب تأكيد بريدك الإلكتروني قبل تسجيل الدخول.",
    welcome: "مرحباً، يتم تحويلك الآن...",
    enterEmail: "اكتب بريدك الإلكتروني أولاً.",
    sendingVerification: "جاري إرسال رابط التحقق...",
    resent: "إذا كان هذا البريد يحتاج تأكيداً، فقد تم إرسال رابط جديد.",
    resendFailed: "تعذر إرسال رابط التحقق.",
    forgotPassword: "نسيت كلمة المرور؟",
    resendVerification: "إعادة إرسال رابط التحقق",
  },
  en: {
    identifier: "Email, username, or phone",
    password: "Password",
    signingIn: "Signing in...",
    failed: "Could not sign in. Check your details and try again.",
    verificationRequired: "Please verify your email before signing in.",
    welcome: "Welcome. Redirecting...",
    enterEmail: "Enter your email first.",
    sendingVerification: "Sending verification link...",
    resent: "If this email needs verification, a new link has been sent.",
    resendFailed: "Could not send verification link.",
    forgotPassword: "Forgot password?",
    resendVerification: "Resend verification email",
  },
  ru: {
    identifier: "Email, имя пользователя или телефон",
    password: "Пароль",
    signingIn: "Вход...",
    failed: "Не удалось войти. Проверьте данные и попробуйте снова.",
    verificationRequired: "Подтвердите email перед входом.",
    welcome: "Добро пожаловать. Перенаправляем...",
    enterEmail: "Сначала введите email.",
    sendingVerification: "Отправляем ссылку подтверждения...",
    resent: "Если этому email нужно подтверждение, новая ссылка отправлена.",
    resendFailed: "Не удалось отправить ссылку подтверждения.",
    forgotPassword: "Забыли пароль?",
    resendVerification: "Отправить подтверждение снова",
  },
  tr: {
    identifier: "E-posta, kullanıcı adı veya telefon",
    password: "Şifre",
    signingIn: "Giriş yapılıyor...",
    failed: "Giriş yapılamadı. Bilgileri kontrol edin.",
    verificationRequired: "Giriş yapmadan önce e-postanızı doğrulayın.",
    welcome: "Hoş geldiniz. Yönlendiriliyor...",
    enterEmail: "Önce e-postanızı yazın.",
    sendingVerification: "Doğrulama bağlantısı gönderiliyor...",
    resent: "Bu e-posta doğrulama gerektiriyorsa yeni bağlantı gönderildi.",
    resendFailed: "Doğrulama bağlantısı gönderilemedi.",
    forgotPassword: "Şifremi unuttum",
    resendVerification: "Doğrulama e-postasını tekrar gönder",
  },
  fr: {
    identifier: "Email, nom d'utilisateur ou téléphone",
    password: "Mot de passe",
    signingIn: "Connexion...",
    failed: "Connexion impossible. Vérifiez vos informations.",
    verificationRequired:
      "Veuillez vérifier votre email avant de vous connecter.",
    welcome: "Bienvenue. Redirection...",
    enterEmail: "Saisissez d'abord votre email.",
    sendingVerification: "Envoi du lien de vérification...",
    resent:
      "Si cet email nécessite une vérification, un nouveau lien a été envoyé.",
    resendFailed: "Impossible d'envoyer le lien de vérification.",
    forgotPassword: "Mot de passe oublié ?",
    resendVerification: "Renvoyer l'email de vérification",
  },
  es: {
    identifier: "Email, usuario o teléfono",
    password: "Contraseña",
    signingIn: "Iniciando sesión...",
    failed: "No se pudo iniciar sesión. Revisa tus datos.",
    verificationRequired: "Verifica tu email antes de iniciar sesión.",
    welcome: "Bienvenido. Redirigiendo...",
    enterEmail: "Escribe primero tu email.",
    sendingVerification: "Enviando enlace de verificación...",
    resent: "Si este email necesita verificación, se envió un nuevo enlace.",
    resendFailed: "No se pudo enviar el enlace de verificación.",
    forgotPassword: "¿Olvidaste tu contraseña?",
    resendVerification: "Reenviar email de verificación",
  },
  de: {
    identifier: "E-Mail, Benutzername oder Telefon",
    password: "Passwort",
    signingIn: "Anmeldung...",
    failed: "Anmeldung fehlgeschlagen. Bitte Daten prüfen.",
    verificationRequired: "Bitte bestätigen Sie Ihre E-Mail vor der Anmeldung.",
    welcome: "Willkommen. Weiterleitung...",
    enterEmail: "Geben Sie zuerst Ihre E-Mail ein.",
    sendingVerification: "Bestätigungslink wird gesendet...",
    resent:
      "Falls diese E-Mail bestätigt werden muss, wurde ein neuer Link gesendet.",
    resendFailed: "Bestätigungslink konnte nicht gesendet werden.",
    forgotPassword: "Passwort vergessen?",
    resendVerification: "Bestätigungs-E-Mail erneut senden",
  },
} as const;

export interface LoginCopy {
  identifier: string;
  password: string;
  signingIn: string;
  failed: string;
  verificationRequired: string;
  welcome: string;
  enterEmail: string;
  sendingVerification: string;
  resent: string;
  resendFailed: string;
  forgotPassword: string;
  resendVerification: string;
}

const extraLoginCopy: Record<string, LoginCopy> = Object.fromEntries(
  [
    [
      "it",
      [
        "Email, username o telefono",
        "Password",
        "Accesso...",
        "Accesso non riuscito. Controlla i dati.",
        "Verifica l'email prima di accedere.",
        "Benvenuto. Reindirizzamento...",
        "Inserisci prima l'email.",
        "Invio link di verifica...",
        "Se serve verifica, e stato inviato un nuovo link.",
        "Impossibile inviare il link.",
        "Password dimenticata?",
        "Reinvia email di verifica",
      ],
    ],
    [
      "pt",
      [
        "Email, usuario ou telefone",
        "Senha",
        "Entrando...",
        "Nao foi possivel entrar. Verifique os dados.",
        "Verifique seu email antes de entrar.",
        "Bem-vindo. Redirecionando...",
        "Digite seu email primeiro.",
        "Enviando link de verificacao...",
        "Se este email precisar de verificacao, um novo link foi enviado.",
        "Nao foi possivel enviar o link.",
        "Esqueceu a senha?",
        "Reenviar email de verificacao",
      ],
    ],
    [
      "zh",
      [
        "邮箱、用户名或电话",
        "密码",
        "正在登录...",
        "无法登录。请检查信息。",
        "请先验证邮箱。",
        "欢迎，正在跳转...",
        "请先输入邮箱。",
        "正在发送验证链接...",
        "如需验证，新的链接已发送。",
        "无法发送验证链接。",
        "忘记密码？",
        "重新发送验证邮件",
      ],
    ],
    [
      "ja",
      [
        "メール、ユーザー名、電話",
        "パスワード",
        "ログイン中...",
        "ログインできません。入力内容を確認してください。",
        "ログイン前にメールを確認してください。",
        "ようこそ。移動します...",
        "先にメールを入力してください。",
        "確認リンクを送信中...",
        "確認が必要な場合、新しいリンクを送信しました。",
        "確認リンクを送信できません。",
        "パスワードを忘れましたか？",
        "確認メールを再送",
      ],
    ],
    [
      "ko",
      [
        "이메일, 사용자 이름 또는 전화",
        "비밀번호",
        "로그인 중...",
        "로그인할 수 없습니다. 정보를 확인하세요.",
        "로그인 전에 이메일을 인증하세요.",
        "환영합니다. 이동 중...",
        "먼저 이메일을 입력하세요.",
        "인증 링크 전송 중...",
        "인증이 필요하면 새 링크가 전송되었습니다.",
        "인증 링크를 보낼 수 없습니다.",
        "비밀번호를 잊으셨나요?",
        "인증 이메일 다시 보내기",
      ],
    ],
    [
      "hi",
      [
        "ईमेल, उपयोगकर्ता नाम या फोन",
        "पासवर्ड",
        "साइन इन हो रहा है...",
        "साइन इन नहीं हुआ। विवरण जांचें।",
        "साइन इन से पहले ईमेल सत्यापित करें।",
        "स्वागत है। रीडायरेक्ट हो रहा है...",
        "पहले ईमेल दर्ज करें।",
        "सत्यापन लिंक भेजा जा रहा है...",
        "यदि सत्यापन चाहिए, नया लिंक भेजा गया।",
        "लिंक नहीं भेजा जा सका।",
        "पासवर्ड भूल गए?",
        "सत्यापन ईमेल फिर भेजें",
      ],
    ],
    [
      "ur",
      [
        "ای میل، صارف نام یا فون",
        "پاس ورڈ",
        "لاگ ان ہو رہا ہے...",
        "لاگ ان نہیں ہو سکا۔ معلومات چیک کریں۔",
        "لاگ ان سے پہلے ای میل تصدیق کریں۔",
        "خوش آمدید۔ منتقل کیا جا رہا ہے...",
        "پہلے ای میل درج کریں۔",
        "تصدیقی لنک بھیجا جا رہا ہے...",
        "اگر تصدیق چاہیے تو نیا لنک بھیج دیا گیا۔",
        "لنک نہیں بھیجا جا سکا۔",
        "پاس ورڈ بھول گئے؟",
        "تصدیقی ای میل دوبارہ بھیجیں",
      ],
    ],
    [
      "fa",
      [
        "ایمیل، نام کاربری یا تلفن",
        "رمز عبور",
        "در حال ورود...",
        "ورود انجام نشد. اطلاعات را بررسی کنید.",
        "قبل از ورود ایمیل را تأیید کنید.",
        "خوش آمدید. در حال انتقال...",
        "ابتدا ایمیل را وارد کنید.",
        "در حال ارسال لینک تأیید...",
        "اگر نیاز به تأیید باشد، لینک جدید ارسال شد.",
        "ارسال لینک ممکن نبود.",
        "رمز عبور را فراموش کرده‌اید؟",
        "ارسال دوباره ایمیل تأیید",
      ],
    ],
    [
      "he",
      [
        "אימייל, שם משתמש או טלפון",
        "סיסמה",
        "מתחבר...",
        "לא ניתן להתחבר. בדוק פרטים.",
        "אמת אימייל לפני התחברות.",
        "ברוך הבא. מעביר...",
        "הזן קודם אימייל.",
        "שולח קישור אימות...",
        "אם נדרש אימות, קישור חדש נשלח.",
        "לא ניתן לשלוח קישור.",
        "שכחת סיסמה?",
        "שלח אימייל אימות שוב",
      ],
    ],
    [
      "id",
      [
        "Email, nama pengguna, atau telepon",
        "Kata sandi",
        "Masuk...",
        "Tidak dapat masuk. Periksa data.",
        "Verifikasi email sebelum masuk.",
        "Selamat datang. Mengalihkan...",
        "Masukkan email dulu.",
        "Mengirim tautan verifikasi...",
        "Jika perlu verifikasi, tautan baru dikirim.",
        "Tidak dapat mengirim tautan.",
        "Lupa kata sandi?",
        "Kirim ulang email verifikasi",
      ],
    ],
    [
      "ms",
      [
        "E-mel, nama pengguna atau telefon",
        "Kata laluan",
        "Sedang masuk...",
        "Tidak dapat masuk. Semak butiran.",
        "Sahkan e-mel sebelum masuk.",
        "Selamat datang. Mengalih...",
        "Masukkan e-mel dahulu.",
        "Menghantar pautan pengesahan...",
        "Jika perlu pengesahan, pautan baharu dihantar.",
        "Tidak dapat menghantar pautan.",
        "Lupa kata laluan?",
        "Hantar semula e-mel pengesahan",
      ],
    ],
    [
      "uk",
      [
        "Email, ім'я користувача або телефон",
        "Пароль",
        "Вхід...",
        "Не вдалося увійти. Перевірте дані.",
        "Підтвердьте email перед входом.",
        "Вітаємо. Перенаправлення...",
        "Спочатку введіть email.",
        "Надсилання посилання...",
        "Якщо потрібне підтвердження, нове посилання надіслано.",
        "Не вдалося надіслати посилання.",
        "Забули пароль?",
        "Надіслати підтвердження ще раз",
      ],
    ],
    [
      "pl",
      [
        "Email, użytkownik lub telefon",
        "Hasło",
        "Logowanie...",
        "Nie można się zalogować. Sprawdź dane.",
        "Potwierdź email przed logowaniem.",
        "Witamy. Przekierowanie...",
        "Najpierw wpisz email.",
        "Wysyłanie linku...",
        "Jeśli email wymaga weryfikacji, wysłano nowy link.",
        "Nie można wysłać linku.",
        "Nie pamiętasz hasła?",
        "Wyślij email weryfikacyjny ponownie",
      ],
    ],
    [
      "nl",
      [
        "E-mail, gebruikersnaam of telefoon",
        "Wachtwoord",
        "Inloggen...",
        "Kan niet inloggen. Controleer gegevens.",
        "Verifieer je e-mail voor inloggen.",
        "Welkom. Doorsturen...",
        "Voer eerst e-mail in.",
        "Verificatielink verzenden...",
        "Als verificatie nodig is, is een nieuwe link verzonden.",
        "Kan link niet verzenden.",
        "Wachtwoord vergeten?",
        "Verificatie-e-mail opnieuw sturen",
      ],
    ],
    [
      "sv",
      [
        "E-post, användarnamn eller telefon",
        "Lösenord",
        "Loggar in...",
        "Kunde inte logga in. Kontrollera uppgifter.",
        "Verifiera e-post före inloggning.",
        "Välkommen. Omdirigerar...",
        "Ange e-post först.",
        "Skickar verifieringslänk...",
        "Om verifiering krävs har ny länk skickats.",
        "Kunde inte skicka länk.",
        "Glömt lösenord?",
        "Skicka verifieringsmejl igen",
      ],
    ],
    [
      "el",
      [
        "Email, όνομα χρήστη ή τηλέφωνο",
        "Κωδικός",
        "Σύνδεση...",
        "Δεν ήταν δυνατή η σύνδεση. Ελέγξτε τα στοιχεία.",
        "Επαληθεύστε email πριν τη σύνδεση.",
        "Καλώς ήρθατε. Ανακατεύθυνση...",
        "Πρώτα εισαγάγετε email.",
        "Αποστολή συνδέσμου...",
        "Αν απαιτείται επαλήθευση, στάλθηκε νέος σύνδεσμος.",
        "Δεν ήταν δυνατή η αποστολή.",
        "Ξεχάσατε κωδικό;",
        "Αποστολή email επαλήθευσης ξανά",
      ],
    ],
    [
      "vi",
      [
        "Email, tên đăng nhập hoặc điện thoại",
        "Mật khẩu",
        "Đang đăng nhập...",
        "Không thể đăng nhập. Kiểm tra thông tin.",
        "Xác minh email trước khi đăng nhập.",
        "Chào mừng. Đang chuyển...",
        "Nhập email trước.",
        "Đang gửi liên kết xác minh...",
        "Nếu cần xác minh, liên kết mới đã được gửi.",
        "Không thể gửi liên kết.",
        "Quên mật khẩu?",
        "Gửi lại email xác minh",
      ],
    ],
    [
      "th",
      [
        "อีเมล ชื่อผู้ใช้ หรือโทรศัพท์",
        "รหัสผ่าน",
        "กำลังเข้าสู่ระบบ...",
        "เข้าสู่ระบบไม่ได้ โปรดตรวจข้อมูล",
        "ยืนยันอีเมลก่อนเข้าสู่ระบบ",
        "ยินดีต้อนรับ กำลังเปลี่ยนหน้า...",
        "กรอกอีเมลก่อน",
        "กำลังส่งลิงก์ยืนยัน...",
        "หากต้องยืนยัน ได้ส่งลิงก์ใหม่แล้ว",
        "ส่งลิงก์ไม่ได้",
        "ลืมรหัสผ่าน?",
        "ส่งอีเมลยืนยันอีกครั้ง",
      ],
    ],
  ].map(([code, values]) => [code, loginFromList(values as string[])]),
);

function loginFromList(values: string[]): LoginCopy {
  return {
    identifier: values[0] ?? "",
    password: values[1] ?? "",
    signingIn: values[2] ?? "",
    failed: values[3] ?? "",
    verificationRequired: values[4] ?? "",
    welcome: values[5] ?? "",
    enterEmail: values[6] ?? "",
    sendingVerification: values[7] ?? "",
    resent: values[8] ?? "",
    resendFailed: values[9] ?? "",
    forgotPassword: values[10] ?? "",
    resendVerification: values[11] ?? "",
  };
}

export function getLoginCopy(language: string): LoginCopy {
  return (
    loginCopy[language as keyof typeof loginCopy] ??
    extraLoginCopy[language] ??
    loginCopy.en
  );
}
