const registrationCopy = {
  ar: {
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    restaurantName: "اسم المطعم",
    username: "اسم المستخدم",
    country: "الدولة",
    city: "المدينة / المحافظة",
    address: "العنوان",
    phone: "رقم الهاتف",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    selectCountry: "اكتب اسم الدولة للبحث",
    selectCity: "اختر الدولة أولاً ثم اكتب المدينة أو المحافظة",
    countryRequired: "اختر الدولة من القائمة أولاً.",
    cityRequired: "اختر المدينة أو المحافظة من القائمة.",
    consent: "أوافق على",
    terms: "شروط الاستخدام",
    privacy: "سياسة الخصوصية",
    creating: "جاري إنشاء الحساب...",
    mismatch: "كلمتا المرور غير متطابقتين",
    created: "تم إنشاء الحساب. يرجى فحص بريدك لتأكيد الحساب قبل تسجيل الدخول.",
    resent: "تم إرسال رابط التحقق مرة أخرى. يرجى فحص بريدك.",
    failed: "فشل التسجيل",
    submitRestaurant: "تسجيل مطعمك",
  },
  en: {
    firstName: "First name",
    lastName: "Last name",
    restaurantName: "Restaurant name",
    username: "Username",
    country: "Country",
    city: "City / province",
    address: "Address",
    phone: "Phone number",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm password",
    selectCountry: "Type country name to search",
    selectCity: "Select a country first, then type city or province",
    countryRequired: "Select a country from the list first.",
    cityRequired: "Select a city or province from the list.",
    consent: "I agree to",
    terms: "Terms of Use",
    privacy: "Privacy Policy",
    creating: "Creating account...",
    mismatch: "Passwords do not match",
    created:
      "Account created. Please check your email to verify the account before signing in.",
    resent: "A verification link was sent again. Please check your email.",
    failed: "Registration failed",
    submitRestaurant: "Register your restaurant",
  },
  ru: {
    firstName: "Имя",
    lastName: "Фамилия",
    restaurantName: "Название ресторана",
    username: "Имя пользователя",
    country: "Страна",
    city: "Город / регион",
    address: "Адрес",
    phone: "Телефон",
    email: "Email",
    password: "Пароль",
    confirmPassword: "Подтвердите пароль",
    selectCountry: "Введите страну для поиска",
    selectCity: "Сначала выберите страну, затем город или регион",
    countryRequired: "Сначала выберите страну из списка.",
    cityRequired: "Выберите город или регион из списка.",
    consent: "Я принимаю",
    terms: "Условия",
    privacy: "Конфиденциальность",
    creating: "Создание аккаунта...",
    mismatch: "Пароли не совпадают",
    created: "Аккаунт создан. Проверьте email для подтверждения.",
    resent: "Ссылка подтверждения отправлена повторно.",
    failed: "Регистрация не удалась",
    submitRestaurant: "Зарегистрировать ресторан",
  },
  tr: {
    firstName: "Ad",
    lastName: "Soyad",
    restaurantName: "Restoran adı",
    username: "Kullanıcı adı",
    country: "Ülke",
    city: "Şehir / il",
    address: "Adres",
    phone: "Telefon numarası",
    email: "E-posta",
    password: "Şifre",
    confirmPassword: "Şifreyi onayla",
    selectCountry: "Ülke seç",
    selectCity: "Önce ülke seç, sonra şehir veya il yaz",
    countryRequired: "Önce listeden ülke seçin.",
    cityRequired: "Listeden şehir veya il seçin.",
    consent: "Kabul ediyorum",
    terms: "Şartlar",
    privacy: "Gizlilik",
    creating: "Hesap oluşturuluyor...",
    mismatch: "Şifreler eşleşmiyor",
    created: "Hesap oluşturuldu. Giriş yapmadan önce e-postanızı doğrulayın.",
    resent: "Doğrulama bağlantısı tekrar gönderildi.",
    failed: "Kayıt başarısız",
    submitRestaurant: "Restoranını kaydet",
  },
  fr: {
    firstName: "Prénom",
    lastName: "Nom",
    restaurantName: "Nom du restaurant",
    username: "Nom d'utilisateur",
    country: "Pays",
    city: "Ville / province",
    address: "Adresse",
    phone: "Téléphone",
    email: "Email",
    password: "Mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    selectCountry: "Choisir le pays",
    selectCity: "Choisissez d'abord un pays, puis la ville ou province",
    countryRequired: "Choisissez d'abord un pays dans la liste.",
    cityRequired: "Choisissez une ville ou province dans la liste.",
    consent: "J'accepte",
    terms: "Conditions",
    privacy: "Confidentialité",
    creating: "Création du compte...",
    mismatch: "Les mots de passe ne correspondent pas",
    created: "Compte créé. Vérifiez votre email avant de vous connecter.",
    resent: "Un nouveau lien de vérification a été envoyé.",
    failed: "Échec de l'inscription",
    submitRestaurant: "Inscrire votre restaurant",
  },
  es: {
    firstName: "Nombre",
    lastName: "Apellido",
    restaurantName: "Nombre del restaurante",
    username: "Usuario",
    country: "País",
    city: "Ciudad / provincia",
    address: "Dirección",
    phone: "Teléfono",
    email: "Email",
    password: "Contraseña",
    confirmPassword: "Confirmar contraseña",
    selectCountry: "Selecciona país",
    selectCity: "Primero selecciona país, luego ciudad o provincia",
    countryRequired: "Selecciona primero un país de la lista.",
    cityRequired: "Selecciona una ciudad o provincia de la lista.",
    consent: "Acepto",
    terms: "Términos",
    privacy: "Privacidad",
    creating: "Creando cuenta...",
    mismatch: "Las contraseñas no coinciden",
    created: "Cuenta creada. Revisa tu email para verificarla.",
    resent: "Se envió nuevamente el enlace de verificación.",
    failed: "Registro fallido",
    submitRestaurant: "Registrar tu restaurante",
  },
  de: {
    firstName: "Vorname",
    lastName: "Nachname",
    restaurantName: "Restaurantname",
    username: "Benutzername",
    country: "Land",
    city: "Stadt / Region",
    address: "Adresse",
    phone: "Telefonnummer",
    email: "E-Mail",
    password: "Passwort",
    confirmPassword: "Passwort bestätigen",
    selectCountry: "Land auswählen",
    selectCity: "Zuerst Land wählen, dann Stadt oder Region",
    countryRequired: "Wählen Sie zuerst ein Land aus der Liste.",
    cityRequired: "Wählen Sie eine Stadt oder Region aus der Liste.",
    consent: "Ich stimme zu",
    terms: "Bedingungen",
    privacy: "Datenschutz",
    creating: "Konto wird erstellt...",
    mismatch: "Passwörter stimmen nicht überein",
    created: "Konto erstellt. Bitte bestätigen Sie Ihre E-Mail.",
    resent: "Der Bestätigungslink wurde erneut gesendet.",
    failed: "Registrierung fehlgeschlagen",
    submitRestaurant: "Restaurant registrieren",
  },
} as const;

export interface RegistrationCopy {
  firstName: string;
  lastName: string;
  restaurantName: string;
  username: string;
  country: string;
  city: string;
  address: string;
  phone: string;
  email: string;
  password: string;
  confirmPassword: string;
  selectCountry: string;
  selectCity: string;
  countryRequired: string;
  cityRequired: string;
  consent: string;
  terms: string;
  privacy: string;
  creating: string;
  mismatch: string;
  created: string;
  resent: string;
  failed: string;
  submitRestaurant: string;
}

const extraRegistrationCopy: Record<string, RegistrationCopy> =
  Object.fromEntries(
    [
      [
        "it",
        [
          "Nome",
          "Cognome",
          "Nome ristorante",
          "Nome utente",
          "Paese",
          "Citta / provincia",
          "Indirizzo",
          "Numero di telefono",
          "Email",
          "Password",
          "Conferma password",
          "Scrivi il nome del paese",
          "Scegli prima il paese, poi citta o provincia",
          "Scegli prima un paese dall'elenco.",
          "Scegli una citta o provincia dall'elenco.",
          "Accetto",
          "Termini",
          "Privacy",
          "Creazione account...",
          "Le password non coincidono",
          "Account creato. Controlla l'email per confermare.",
          "Link di verifica inviato di nuovo.",
          "Registrazione non riuscita",
          "Registra il tuo ristorante",
        ],
      ],
      [
        "pt",
        [
          "Nome",
          "Sobrenome",
          "Nome do restaurante",
          "Usuario",
          "Pais",
          "Cidade / provincia",
          "Endereco",
          "Telefone",
          "Email",
          "Senha",
          "Confirmar senha",
          "Digite o pais para buscar",
          "Escolha primeiro o pais, depois cidade ou provincia",
          "Escolha primeiro um pais da lista.",
          "Escolha uma cidade ou provincia da lista.",
          "Eu aceito",
          "Termos",
          "Privacidade",
          "Criando conta...",
          "As senhas nao coincidem",
          "Conta criada. Verifique seu email para confirmar.",
          "Link de verificacao enviado novamente.",
          "Falha no registro",
          "Registrar seu restaurante",
        ],
      ],
      [
        "zh",
        [
          "名字",
          "姓氏",
          "餐厅名称",
          "用户名",
          "国家",
          "城市 / 省份",
          "地址",
          "电话号码",
          "邮箱",
          "密码",
          "确认密码",
          "输入国家名称搜索",
          "先选择国家，再输入城市或省份",
          "请先从列表选择国家。",
          "请从列表选择城市或省份。",
          "我同意",
          "使用条款",
          "隐私政策",
          "正在创建账户...",
          "两次密码不一致",
          "账户已创建。请检查邮箱完成验证。",
          "验证链接已重新发送。",
          "注册失败",
          "注册你的餐厅",
        ],
      ],
      [
        "ja",
        [
          "名",
          "姓",
          "レストラン名",
          "ユーザー名",
          "国",
          "市区町村 / 都道府県",
          "住所",
          "電話番号",
          "メール",
          "パスワード",
          "パスワード確認",
          "国名を入力して検索",
          "先に国を選択し、市区町村を入力",
          "先に一覧から国を選択してください。",
          "一覧から市区町村または地域を選択してください。",
          "同意します",
          "利用規約",
          "プライバシー",
          "アカウント作成中...",
          "パスワードが一致しません",
          "アカウントを作成しました。メールを確認してください。",
          "確認リンクを再送しました。",
          "登録に失敗しました",
          "レストランを登録",
        ],
      ],
      [
        "ko",
        [
          "이름",
          "성",
          "레스토랑 이름",
          "사용자 이름",
          "국가",
          "도시 / 지역",
          "주소",
          "전화번호",
          "이메일",
          "비밀번호",
          "비밀번호 확인",
          "국가명을 입력해 검색",
          "먼저 국가를 선택한 뒤 도시나 지역 입력",
          "먼저 목록에서 국가를 선택하세요.",
          "목록에서 도시 또는 지역을 선택하세요.",
          "동의합니다",
          "이용 약관",
          "개인정보",
          "계정 생성 중...",
          "비밀번호가 일치하지 않습니다",
          "계정이 생성되었습니다. 이메일을 확인하세요.",
          "인증 링크를 다시 보냈습니다.",
          "등록 실패",
          "레스토랑 등록",
        ],
      ],
      [
        "hi",
        [
          "पहला नाम",
          "अंतिम नाम",
          "रेस्तरां नाम",
          "उपयोगकर्ता नाम",
          "देश",
          "शहर / प्रांत",
          "पता",
          "फोन नंबर",
          "ईमेल",
          "पासवर्ड",
          "पासवर्ड पुष्टि",
          "देश खोजने के लिए नाम लिखें",
          "पहले देश चुनें, फिर शहर या प्रांत लिखें",
          "पहले सूची से देश चुनें।",
          "सूची से शहर या प्रांत चुनें।",
          "मैं सहमत हूं",
          "उपयोग की शर्तें",
          "गोपनीयता नीति",
          "खाता बनाया जा रहा है...",
          "पासवर्ड मेल नहीं खाते",
          "खाता बना। ईमेल सत्यापित करें।",
          "सत्यापन लिंक फिर भेजा गया।",
          "पंजीकरण विफल",
          "अपना रेस्तरां पंजीकृत करें",
        ],
      ],
      [
        "ur",
        [
          "پہلا نام",
          "آخری نام",
          "ریستوران کا نام",
          "صارف نام",
          "ملک",
          "شہر / صوبہ",
          "پتہ",
          "فون نمبر",
          "ای میل",
          "پاس ورڈ",
          "پاس ورڈ کی تصدیق",
          "ملک تلاش کرنے کے لیے نام لکھیں",
          "پہلے ملک منتخب کریں، پھر شہر یا صوبہ لکھیں",
          "پہلے فہرست سے ملک منتخب کریں۔",
          "فہرست سے شہر یا صوبہ منتخب کریں۔",
          "میں متفق ہوں",
          "استعمال کی شرائط",
          "رازداری پالیسی",
          "اکاؤنٹ بنایا جا رہا ہے...",
          "پاس ورڈ میل نہیں کھاتے",
          "اکاؤنٹ بن گیا۔ ای میل تصدیق کریں۔",
          "تصدیقی لنک دوبارہ بھیجا گیا۔",
          "رجسٹریشن ناکام",
          "اپنا ریستوران رجسٹر کریں",
        ],
      ],
      [
        "fa",
        [
          "نام",
          "نام خانوادگی",
          "نام رستوران",
          "نام کاربری",
          "کشور",
          "شهر / استان",
          "آدرس",
          "شماره تلفن",
          "ایمیل",
          "رمز عبور",
          "تکرار رمز عبور",
          "نام کشور را برای جستجو بنویسید",
          "ابتدا کشور را انتخاب کنید، سپس شهر یا استان را بنویسید",
          "ابتدا کشور را از فهرست انتخاب کنید.",
          "شهر یا استان را از فهرست انتخاب کنید.",
          "موافقم",
          "شرایط استفاده",
          "حریم خصوصی",
          "در حال ایجاد حساب...",
          "رمزها یکسان نیستند",
          "حساب ایجاد شد. ایمیل را تأیید کنید.",
          "لینک تأیید دوباره ارسال شد.",
          "ثبت نام ناموفق بود",
          "رستوران خود را ثبت کنید",
        ],
      ],
      [
        "he",
        [
          "שם פרטי",
          "שם משפחה",
          "שם המסעדה",
          "שם משתמש",
          "מדינה",
          "עיר / מחוז",
          "כתובת",
          "טלפון",
          "אימייל",
          "סיסמה",
          "אישור סיסמה",
          "הקלד שם מדינה לחיפוש",
          "בחר קודם מדינה ואז עיר או מחוז",
          "בחר קודם מדינה מהרשימה.",
          "בחר עיר או מחוז מהרשימה.",
          "אני מסכים",
          "תנאי שימוש",
          "פרטיות",
          "יוצר חשבון...",
          "הסיסמאות אינן תואמות",
          "החשבון נוצר. אשר את האימייל.",
          "קישור אימות נשלח שוב.",
          "הרישום נכשל",
          "רשום את המסעדה שלך",
        ],
      ],
      [
        "id",
        [
          "Nama depan",
          "Nama belakang",
          "Nama restoran",
          "Nama pengguna",
          "Negara",
          "Kota / provinsi",
          "Alamat",
          "Nomor telepon",
          "Email",
          "Kata sandi",
          "Konfirmasi kata sandi",
          "Ketik nama negara untuk mencari",
          "Pilih negara dulu, lalu kota atau provinsi",
          "Pilih negara dari daftar dulu.",
          "Pilih kota atau provinsi dari daftar.",
          "Saya setuju",
          "Ketentuan",
          "Privasi",
          "Membuat akun...",
          "Kata sandi tidak cocok",
          "Akun dibuat. Periksa email Anda.",
          "Tautan verifikasi dikirim lagi.",
          "Pendaftaran gagal",
          "Daftarkan restoran Anda",
        ],
      ],
      [
        "ms",
        [
          "Nama pertama",
          "Nama keluarga",
          "Nama restoran",
          "Nama pengguna",
          "Negara",
          "Bandar / negeri",
          "Alamat",
          "Nombor telefon",
          "E-mel",
          "Kata laluan",
          "Sahkan kata laluan",
          "Taip nama negara untuk carian",
          "Pilih negara dahulu, kemudian bandar atau negeri",
          "Pilih negara daripada senarai dahulu.",
          "Pilih bandar atau negeri daripada senarai.",
          "Saya bersetuju",
          "Terma",
          "Privasi",
          "Mencipta akaun...",
          "Kata laluan tidak sepadan",
          "Akaun dicipta. Semak e-mel anda.",
          "Pautan pengesahan dihantar semula.",
          "Pendaftaran gagal",
          "Daftar restoran anda",
        ],
      ],
      [
        "uk",
        [
          "Ім'я",
          "Прізвище",
          "Назва ресторану",
          "Ім'я користувача",
          "Країна",
          "Місто / область",
          "Адреса",
          "Телефон",
          "Email",
          "Пароль",
          "Підтвердіть пароль",
          "Введіть країну для пошуку",
          "Спочатку виберіть країну, потім місто або область",
          "Спочатку виберіть країну зі списку.",
          "Виберіть місто або область зі списку.",
          "Я погоджуюся",
          "Умови",
          "Приватність",
          "Створення акаунта...",
          "Паролі не збігаються",
          "Акаунт створено. Перевірте email.",
          "Посилання підтвердження надіслано знову.",
          "Реєстрація не вдалася",
          "Зареєструвати ресторан",
        ],
      ],
      [
        "pl",
        [
          "Imię",
          "Nazwisko",
          "Nazwa restauracji",
          "Nazwa użytkownika",
          "Kraj",
          "Miasto / województwo",
          "Adres",
          "Telefon",
          "Email",
          "Hasło",
          "Potwierdź hasło",
          "Wpisz kraj, aby wyszukać",
          "Najpierw wybierz kraj, potem miasto lub region",
          "Najpierw wybierz kraj z listy.",
          "Wybierz miasto lub region z listy.",
          "Akceptuję",
          "Warunki",
          "Prywatność",
          "Tworzenie konta...",
          "Hasła nie są zgodne",
          "Konto utworzone. Sprawdź email.",
          "Link weryfikacyjny wysłano ponownie.",
          "Rejestracja nie powiodła się",
          "Zarejestruj restaurację",
        ],
      ],
      [
        "nl",
        [
          "Voornaam",
          "Achternaam",
          "Restaurantnaam",
          "Gebruikersnaam",
          "Land",
          "Stad / provincie",
          "Adres",
          "Telefoonnummer",
          "E-mail",
          "Wachtwoord",
          "Bevestig wachtwoord",
          "Typ landnaam om te zoeken",
          "Kies eerst land, daarna stad of provincie",
          "Kies eerst een land uit de lijst.",
          "Kies een stad of provincie uit de lijst.",
          "Ik ga akkoord",
          "Voorwaarden",
          "Privacy",
          "Account maken...",
          "Wachtwoorden komen niet overeen",
          "Account gemaakt. Controleer je e-mail.",
          "Verificatielink opnieuw verzonden.",
          "Registratie mislukt",
          "Registreer je restaurant",
        ],
      ],
      [
        "sv",
        [
          "Förnamn",
          "Efternamn",
          "Restaurangnamn",
          "Användarnamn",
          "Land",
          "Stad / region",
          "Adress",
          "Telefonnummer",
          "E-post",
          "Lösenord",
          "Bekräfta lösenord",
          "Skriv land för att söka",
          "Välj först land, sedan stad eller region",
          "Välj först ett land i listan.",
          "Välj stad eller region i listan.",
          "Jag godkänner",
          "Villkor",
          "Integritet",
          "Skapar konto...",
          "Lösenorden matchar inte",
          "Konto skapat. Kontrollera e-post.",
          "Verifieringslänk skickad igen.",
          "Registrering misslyckades",
          "Registrera din restaurang",
        ],
      ],
      [
        "el",
        [
          "Όνομα",
          "Επώνυμο",
          "Όνομα εστιατορίου",
          "Όνομα χρήστη",
          "Χώρα",
          "Πόλη / περιφέρεια",
          "Διεύθυνση",
          "Τηλέφωνο",
          "Email",
          "Κωδικός",
          "Επιβεβαίωση κωδικού",
          "Πληκτρολογήστε χώρα για αναζήτηση",
          "Επιλέξτε πρώτα χώρα, μετά πόλη ή περιφέρεια",
          "Επιλέξτε πρώτα χώρα από τη λίστα.",
          "Επιλέξτε πόλη ή περιφέρεια από τη λίστα.",
          "Συμφωνώ",
          "Όροι",
          "Απόρρητο",
          "Δημιουργία λογαριασμού...",
          "Οι κωδικοί δεν ταιριάζουν",
          "Ο λογαριασμός δημιουργήθηκε. Ελέγξτε email.",
          "Ο σύνδεσμος επαλήθευσης στάλθηκε ξανά.",
          "Η εγγραφή απέτυχε",
          "Εγγραφή εστιατορίου",
        ],
      ],
      [
        "vi",
        [
          "Tên",
          "Họ",
          "Tên nhà hàng",
          "Tên đăng nhập",
          "Quốc gia",
          "Thành phố / tỉnh",
          "Địa chỉ",
          "Số điện thoại",
          "Email",
          "Mật khẩu",
          "Xác nhận mật khẩu",
          "Nhập tên quốc gia để tìm",
          "Chọn quốc gia trước, rồi nhập thành phố hoặc tỉnh",
          "Trước tiên chọn quốc gia từ danh sách.",
          "Chọn thành phố hoặc tỉnh từ danh sách.",
          "Tôi đồng ý",
          "Điều khoản",
          "Quyền riêng tư",
          "Đang tạo tài khoản...",
          "Mật khẩu không khớp",
          "Tài khoản đã tạo. Kiểm tra email.",
          "Đã gửi lại liên kết xác minh.",
          "Đăng ký thất bại",
          "Đăng ký nhà hàng",
        ],
      ],
      [
        "th",
        [
          "ชื่อ",
          "นามสกุล",
          "ชื่อร้านอาหาร",
          "ชื่อผู้ใช้",
          "ประเทศ",
          "เมือง / จังหวัด",
          "ที่อยู่",
          "เบอร์โทรศัพท์",
          "อีเมล",
          "รหัสผ่าน",
          "ยืนยันรหัสผ่าน",
          "พิมพ์ชื่อประเทศเพื่อค้นหา",
          "เลือกประเทศก่อน แล้วพิมพ์เมืองหรือจังหวัด",
          "เลือกประเทศจากรายการก่อน",
          "เลือกเมืองหรือจังหวัดจากรายการ",
          "ฉันยอมรับ",
          "ข้อกำหนด",
          "ความเป็นส่วนตัว",
          "กำลังสร้างบัญชี...",
          "รหัสผ่านไม่ตรงกัน",
          "สร้างบัญชีแล้ว โปรดตรวจอีเมล",
          "ส่งลิงก์ยืนยันอีกครั้งแล้ว",
          "ลงทะเบียนไม่สำเร็จ",
          "ลงทะเบียนร้านอาหาร",
        ],
      ],
    ].map(([code, values]) => [code, registrationFromList(values as string[])]),
  );

function registrationFromList(values: string[]): RegistrationCopy {
  return {
    firstName: values[0] ?? "",
    lastName: values[1] ?? "",
    restaurantName: values[2] ?? "",
    username: values[3] ?? "",
    country: values[4] ?? "",
    city: values[5] ?? "",
    address: values[6] ?? "",
    phone: values[7] ?? "",
    email: values[8] ?? "",
    password: values[9] ?? "",
    confirmPassword: values[10] ?? "",
    selectCountry: values[11] ?? "",
    selectCity: values[12] ?? "",
    countryRequired: values[13] ?? "",
    cityRequired: values[14] ?? "",
    consent: values[15] ?? "",
    terms: values[16] ?? "",
    privacy: values[17] ?? "",
    creating: values[18] ?? "",
    mismatch: values[19] ?? "",
    created: values[20] ?? "",
    resent: values[21] ?? "",
    failed: values[22] ?? "",
    submitRestaurant: values[23] ?? "",
  };
}

export function getRegistrationCopy(language: string): RegistrationCopy {
  return (
    registrationCopy[language as keyof typeof registrationCopy] ??
    extraRegistrationCopy[language] ??
    registrationCopy.en
  );
}
