import { StyleSheet } from "react-native";
import { colors } from "./theme";

const {
  accent,
  background: bg,
  ink,
  deep,
  card,
  cardSoft,
  brandGreen,
  line,
  nav,
  muted
} = colors;

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: bg },
  appFrame: { flex: 1 },
  rtl: { direction: "rtl" },
  fullScreen: { flex: 1, backgroundColor: bg },
  screenPad: { flex: 1, backgroundColor: bg, paddingHorizontal: 32 },
  onboardingScreen: { flex: 1, backgroundColor: bg, paddingHorizontal: 32 },
  centered: { flex: 1, alignItems: "center", justifyContent: "center", gap: 16 },
  loadingText: { color: ink, fontSize: 18 },
  top: { minHeight: 72, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 28 },
  backButton: { width: 36, height: 40, justifyContent: "center" },
  backText: { color: ink, fontSize: 42, lineHeight: 40, fontWeight: "600" },
  screenTitle: { color: brandGreen, fontSize: 26, fontWeight: "800" },
  language: { color: ink, fontSize: 16, fontWeight: "700" },
  langSpace: { width: 80 },
  languageHero: { marginTop: 76, gap: 20, alignItems: "center" },
  logoMark: { color: brandGreen, fontSize: 36, fontWeight: "900" },
  languageGrid: { gap: 14, paddingTop: 42, paddingBottom: 140 },
  languageChip: { minHeight: 76, borderRadius: 24, backgroundColor: card, justifyContent: "center", paddingHorizontal: 28, borderWidth: 1, borderColor: line, shadowColor: "#cbd8d2", shadowOpacity: 0.35, shadowRadius: 16, shadowOffset: { width: 0, height: 8 } },
  languageChipActive: { backgroundColor: deep, borderColor: deep },
  languageChipText: { color: ink, fontSize: 24, fontWeight: "900" },
  languageChipTextActive: { color: "#fff", fontWeight: "700" },
  languageStrip: { gap: 8, paddingHorizontal: 32, paddingBottom: 10 },
  languagePill: { borderWidth: 1, borderColor: line, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 6, backgroundColor: card },
  languagePillActive: { backgroundColor: deep, borderColor: deep },
  languagePillText: { color: ink, fontSize: 13, fontWeight: "700" },
  languagePillTextActive: { color: "#fff" },
  authContainer: { flex: 1, margin: 16, paddingHorizontal: 28, gap: 16, backgroundColor: card, borderRadius: 28, borderWidth: 1, borderColor: line },
  spinner: { alignSelf: "center", width: 92, height: 92, borderRadius: 46, borderWidth: 10, borderColor: accent, borderLeftColor: "transparent", borderBottomColor: "transparent", marginTop: 26 },
  authTitle: { color: ink, fontSize: 30, textAlign: "center", fontWeight: "800" },
  authSub: { color: muted, fontSize: 16, textAlign: "center", lineHeight: 23 },
  segment: { height: 64, borderRadius: 20, backgroundColor: cardSoft, flexDirection: "row", padding: 5 },
  segmentButton: { flex: 1, alignItems: "center", justifyContent: "center", borderRadius: 6 },
  segmentActive: { backgroundColor: deep },
  segmentText: { color: ink, fontSize: 18, fontWeight: "800" },
  segmentTextActive: { color: "#fff" },
  lineInput: { minHeight: 58, borderWidth: 1, borderColor: line, color: ink, fontSize: 18, paddingHorizontal: 18, borderRadius: 18, backgroundColor: "#fbfdfc" },
  rememberRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  checkbox: { width: 24, height: 24, borderRadius: 7, borderWidth: 2, borderColor: "#92a19c", alignItems: "center", justifyContent: "center" },
  checkboxChecked: { backgroundColor: brandGreen, borderColor: brandGreen },
  checkMark: { color: "#fff", fontSize: 16, fontWeight: "900" },
  rememberText: { color: ink, fontSize: 17 },
  consentRow: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  consentText: { color: ink, flex: 1, fontSize: 14, lineHeight: 21 },
  consentLink: { color: brandGreen, fontWeight: "900", textDecorationLine: "underline" },
  orangeButton: { minHeight: 58, borderRadius: 18, alignItems: "center", justifyContent: "center", backgroundColor: brandGreen, paddingHorizontal: 18 },
  orangeButtonText: { color: "#fff", fontSize: 24, textAlign: "center" },
  buttonDisabled: { backgroundColor: "#c5a77e" },
  link: { color: brandGreen, textAlign: "center", fontSize: 16, fontWeight: "800" },
  errorText: { color: "#a43f3f", textAlign: "center", fontSize: 14, lineHeight: 20 },
  bottomButtonSlot: { position: "absolute", left: 32, right: 32, bottom: 28, zIndex: 20, elevation: 20 },
  centerTitle: { color: ink, fontSize: 30, textAlign: "center", marginTop: 26, fontWeight: "800" },
  scanTitle: { color: muted, textAlign: "center", fontSize: 21, lineHeight: 29, marginTop: 80, marginBottom: 42 },
  qrCard: { alignSelf: "center", borderRadius: 22, padding: 13, backgroundColor: card, borderWidth: 1, borderColor: line },
  qrImage: { width: 284, height: 284 },
  homeHeader: { alignItems: "center", marginTop: 70, gap: 18, paddingHorizontal: 28 },
  logoText: { color: brandGreen, textAlign: "center", fontSize: 30, fontWeight: "900" },
  restaurantHint: { color: muted, textAlign: "center", fontSize: 15 },
  homeActions: { marginTop: 110, paddingHorizontal: 32, gap: 34 },
  bigArrow: { height: 84, borderRadius: 22, backgroundColor: card, borderWidth: 1, borderColor: line, paddingHorizontal: 20, flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  bigArrowText: { color: ink, fontSize: 25, fontWeight: "800" },
  bigArrowIcon: { color: accent, fontSize: 45 },
  waiterBody: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 32, paddingBottom: 110 },
  waiterIcon: { fontSize: 120 },
  waiterText: { color: ink, textAlign: "center", fontSize: 26, lineHeight: 34, fontWeight: "700" },
  bottomNav: { position: "absolute", left: 0, right: 0, bottom: 0, height: 51, backgroundColor: nav, flexDirection: "row", justifyContent: "space-around", alignItems: "center" },
  tab: { alignItems: "center", minWidth: 62, maxWidth: 82 },
  tabIcon: { color: accent, fontSize: 24 },
  tabLabel: { color: accent, fontSize: 7, maxWidth: 78 },
  tabActive: { color: accent },
  menuContent: { paddingHorizontal: 32, paddingBottom: 170 },
  restaurantName: { color: ink, fontSize: 34, marginBottom: 14, fontWeight: "900" },
  search: { minHeight: 54, borderRadius: 18, paddingHorizontal: 18, color: ink, backgroundColor: card, borderWidth: 1, borderColor: line, fontSize: 16 },
  restaurantStrip: { gap: 8, paddingTop: 12 },
  restaurantChip: { borderWidth: 1, borderColor: line, borderRadius: 20, paddingHorizontal: 18, paddingVertical: 13, backgroundColor: card },
  restaurantChipActive: { backgroundColor: deep, borderColor: deep },
  restaurantChipText: { color: ink, fontSize: 16, fontWeight: "800" },
  restaurantChipTextActive: { color: "#fff" },
  bannerRow: { gap: 8, paddingTop: 24, paddingBottom: 28 },
  banner: { width: 174, height: 100, borderWidth: 1, borderColor: line, borderRadius: 18, backgroundColor: card, padding: 12 },
  bannerPhoto: { backgroundColor: "#172820" },
  bannerDiscount: { color: "#fff", backgroundColor: accent, fontSize: 9, alignSelf: "flex-start" },
  bannerText: { color: ink, fontSize: 14, fontWeight: "800" },
  happy: { color: "#fff", fontSize: 18, fontWeight: "900" },
  toggleRow: { flexDirection: "row", justifyContent: "space-around", marginBottom: 14 },
  toggleOff: { color: muted, fontSize: 17 },
  toggleOn: { color: brandGreen, fontSize: 20, fontWeight: "900" },
  oftenRow: { gap: 12, paddingBottom: 64, paddingTop: 36 },
  smallFood: { width: 122, minHeight: 196, borderWidth: 1, borderColor: line, borderRadius: 24, backgroundColor: card, paddingHorizontal: 12, paddingTop: 62 },
  smallFoodImage: { position: "absolute", top: -36, alignSelf: "center", width: 82, height: 82, borderRadius: 41 },
  smallFoodName: { color: ink, fontSize: 17, lineHeight: 19, fontWeight: "900" },
  smallFoodDescription: { color: muted, fontSize: 10, lineHeight: 14, marginTop: 7 },
  priceRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: "auto" },
  oldPrice: { color: "#fff", fontSize: 10, textDecorationLine: "line-through" },
  priceOrange: { color: accent, fontSize: 18 },
  plusCircle: { color: accent, borderWidth: 1, borderColor: accent, borderRadius: 10, width: 20, height: 20, textAlign: "center", lineHeight: 18, fontSize: 17 },
  grid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", rowGap: 82 },
  largeFood: { width: "100%", minHeight: 150, borderWidth: 1, borderColor: line, borderRadius: 24, backgroundColor: card, paddingHorizontal: 24, paddingVertical: 18, paddingRight: 150 },
  largeFoodImage: { position: "absolute", right: 24, top: 20, width: 112, height: 112, borderRadius: 24 },
  largeFoodName: { color: ink, fontSize: 25, lineHeight: 31, fontWeight: "900" },
  largeFoodDescription: { color: muted, fontSize: 16, lineHeight: 23, marginTop: 6 },
  largePrice: { color: ink, fontSize: 21, fontWeight: "900" },
  floatingBasket: { position: "absolute", right: 32, bottom: 120, width: 58, height: 58, borderRadius: 29, backgroundColor: deep, alignItems: "center", justifyContent: "center", shadowColor: "#000", shadowOpacity: 0.2, shadowRadius: 10 },
  floatingBasketText: { fontSize: 28 },
  cartBadge: { position: "absolute", top: -4, right: -4, minWidth: 20, height: 20, borderRadius: 10, overflow: "hidden", backgroundColor: accent, color: "#fff", textAlign: "center", fontSize: 12, lineHeight: 20, fontWeight: "700" },
  detailScroll: { paddingBottom: 64 },
  detailImage: { alignSelf: "center", width: 242, height: 242, borderRadius: 121, marginTop: 10, zIndex: 2 },
  detailCard: { marginTop: -20, borderTopLeftRadius: 34, borderTopRightRadius: 34, backgroundColor: card, padding: 32, paddingTop: 58, minHeight: 520, borderWidth: 1, borderColor: line },
  detailName: { color: ink, fontSize: 34, lineHeight: 42, fontWeight: "900" },
  calorieRow: { flexDirection: "row", gap: 22, marginTop: 16, alignItems: "center" },
  calories: { color: ink, fontSize: 17 },
  badge: { color: accent, borderColor: accent, borderWidth: 1, borderRadius: 12, paddingHorizontal: 8, fontSize: 16 },
  orangeHeading: { color: accent, fontSize: 26, marginTop: 22 },
  detailDescription: { color: muted, fontSize: 17, lineHeight: 25, marginTop: 10 },
  counter: { marginTop: 22, marginBottom: 18, width: 78, height: 32, borderWidth: 1, borderColor: accent, borderRadius: 14, flexDirection: "row", justifyContent: "space-around", alignItems: "center" },
  counterText: { color: ink, fontSize: 22 },
  ingredientGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", rowGap: 12, marginTop: 18 },
  ingredientItem: { width: 70, alignItems: "center" },
  ingredientDot: { color: accent, fontSize: 24 },
  ingredientText: { color: ink, fontSize: 9, marginTop: 3, textAlign: "center" },
  addMini: { backgroundColor: accent, borderRadius: 4, width: 58, height: 20, justifyContent: "center", marginTop: 4 },
  addMiniText: { color: "#fff", textAlign: "center", fontSize: 8 },
  pageContent: { flex: 1, paddingHorizontal: 32, paddingTop: 22 },
  pageScroll: { paddingHorizontal: 32, paddingTop: 22, paddingBottom: 100 },
  sectionTitle: { color: ink, fontSize: 26, marginBottom: 24, marginTop: 18, fontWeight: "900" },
  orderLine: { minHeight: 104, borderRadius: 22, backgroundColor: card, borderWidth: 1, borderColor: line, marginBottom: 10, paddingHorizontal: 22, flexDirection: "row", alignItems: "center", gap: 16 },
  orderImage: { width: 70, height: 70, borderRadius: 35 },
  orderBody: { flex: 1 },
  orderName: { color: ink, fontSize: 17, fontWeight: "900" },
  orderQty: { color: ink, fontSize: 17, marginTop: 20 },
  orderPrice: { color: ink, fontSize: 18, fontWeight: "900" },
  lineCounter: { marginTop: 12, width: 74, height: 24, borderColor: accent, borderWidth: 1, borderRadius: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-around" },
  lineCounterText: { color: ink, fontSize: 16 },
  totalText: { color: ink, fontSize: 18, alignSelf: "flex-end", marginTop: 12, fontWeight: "900" },
  noteInput: { minHeight: 56, borderColor: line, borderWidth: 1, color: ink, borderRadius: 16, paddingHorizontal: 14, marginTop: 10, backgroundColor: card },
  emptyBasket: { flex: 1, alignItems: "center", justifyContent: "center", paddingBottom: 110 },
  emptyCup: { color: brandGreen, fontSize: 120 },
  emptyText: { color: ink, fontSize: 25, marginTop: 16, textAlign: "center", fontWeight: "800" },
  emptySmall: { color: muted, fontSize: 18, textAlign: "center" },
  radioRow: { flexDirection: "row", alignItems: "center", gap: 16, marginBottom: 22 },
  radioOuter: { width: 24, height: 24, borderRadius: 12, borderWidth: 1, borderColor: "#fff", justifyContent: "center", alignItems: "center" },
  radioOuterActive: { borderColor: accent },
  radioInner: { width: 12, height: 12, borderRadius: 6, backgroundColor: accent },
  radioLabel: { color: ink, fontSize: 25, fontWeight: "700" },
  cardChoiceRow: { flexDirection: "row", gap: 8, marginBottom: 32 },
  cardChoice: { width: 104, height: 62, borderRadius: 4, backgroundColor: card, alignItems: "center", justifyContent: "center" },
  cardChoiceActive: { borderWidth: 1, borderColor: accent, backgroundColor: "#fff", shadowColor: "#fff", shadowOpacity: 0.6, shadowRadius: 12 },
  visaText: { color: "#0036a4", fontWeight: "900", fontSize: 20 },
  masterText: { color: "#d21f2b", fontSize: 11, fontWeight: "900" },
  creditCard: { height: 198, borderRadius: 6, padding: 22, backgroundColor: "#77d4ba", justifyContent: "space-between" },
  cardLabel: { color: "#16352b", fontSize: 8 },
  cardInput: { height: 24, backgroundColor: "#fff", borderRadius: 2, marginTop: 5 },
  cardHolder: { width: 156 },
  cardBottom: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end" },
  cashList: { marginTop: 12 },
  paymentAmount: { color: ink, marginTop: 32, fontSize: 16, fontWeight: "800" },
  amount: { color: accent, fontSize: 25 },
  successBody: { flex: 1, alignItems: "center", justifyContent: "center", gap: 24 },
  successCircle: { width: 100, height: 100, borderRadius: 50, alignItems: "center", justifyContent: "center", backgroundColor: accent },
  successCheck: { color: "#fff", fontSize: 76 },
  thanksTitle: { color: ink, fontSize: 25, textAlign: "center", fontWeight: "900" },
  thanksSub: { color: muted, textAlign: "center", fontSize: 17, lineHeight: 24 },
  pastTitle: { marginTop: 32 },
  statusOrange: { color: accent, fontSize: 16, marginTop: 4 },
  profileHeader: { flexDirection: "row", gap: 30, alignItems: "center", paddingHorizontal: 32, marginTop: 20 },
  avatar: { width: 92, height: 92, borderRadius: 46, borderWidth: 1, borderColor: accent },
  profileName: { color: accent, fontSize: 25 },
  profileMeta: { color: muted, fontSize: 17, marginTop: 8 },
  profileList: { paddingHorizontal: 32, marginTop: 60, gap: 22 },
  profileMain: { color: ink, fontSize: 17, fontWeight: "900" },
  profileLink: { color: ink, fontSize: 16 },
  profileLanguageGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  profileLanguageButton: { backgroundColor: card, borderWidth: 1, borderColor: line, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 7 },
  profileLanguageText: { color: ink, fontSize: 12, fontWeight: "800" }
});
