FROM node:22-alpine

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1
ENV NPM_CONFIG_AUDIT=false
ENV NPM_CONFIG_FUND=false

COPY package*.json ./
COPY tsconfig.base.json ./
COPY apps ./apps
COPY services ./services
COPY packages ./packages

RUN npm ci --no-audit --no-fund

CMD ["npm", "run", "dev:web"]
