FROM node:22-alpine

WORKDIR /app

ARG COOLIFY_FQDN
ARG REDIS_PASSWORD
ARG POSTGRES_PASSWORD
ARG SERVICE_URL_WEB
ARG SERVICE_FQDN_WEB
ARG SERVICE_URL_API_GATEWAY
ARG SERVICE_FQDN_API_GATEWAY
ARG AUTH_TOKEN_SECRET
ARG SESSION_SECRET
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_SECURE
ARG SMTP_USER
ARG SMTP_PASSWORD
ARG SMTP_FROM
ARG PUBLIC_WEB_URL
ARG PUBLIC_API_URL
ARG COOLIFY_BUILD_SECRETS_HASH
ARG NEXT_PUBLIC_API_URL
ARG WEB_PUBLIC_API_URL

ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV WEB_PUBLIC_API_URL=${WEB_PUBLIC_API_URL}
ENV NEXT_TELEMETRY_DISABLED=1
ENV NPM_CONFIG_AUDIT=false
ENV NPM_CONFIG_FUND=false

COPY package*.json ./
COPY tsconfig.base.json ./
COPY apps ./apps
COPY services ./services
COPY packages ./packages

RUN npm ci --no-audit --no-fund
RUN npm run build -w @babili/shared
RUN npm run build --workspaces --if-present
RUN npm prune --omit=dev --no-audit --no-fund && npm cache clean --force

CMD ["npm", "run", "start", "-w", "@babili/api-gateway"]
